### ISSUE TITLE
Issue with the plugin history-substring-search

### ISSUE THREAD

**Issue by b-per** [dracula/zsh#27]
Hi,

I just switched my ZSH them to dracula and realised that the plugin `history-substring-search` stopped working at the same time. This plugin allows searching in the history with up/down arrows filtering on only the commands containing the text already typed.

From what I can see in [this issue](https://github.com/ohmyzsh/ohmyzsh/issues/4540), this is related to the definition of the function `zle-line-init` in the ZSH dracula theme.

**Comment by romellem** [comment]
I was recently setting up a new computer and ran into this same issue.

This obviously isn't a solution, but for me, another computer I had was working normally and I realized that computer's `dracula/zsh` version was fairly out of date. It was checked out to 22058079469b74af07f1f4984df505f9b5156c1f.

I'm sure there have been lots of bug fixes since that commit, but otherwise, switching to that point is enough for me as a hacky sort of workaround.

```
git checkout 22058079
```

**Comment by b-per** [comment]
On my side, I am using master but then have changed the definition and call to `zle-line-init` to `zle-line-init-dracula` in `dracula.zsh-theme` and it works out fine.

**Comment by AGitBoy** [comment]
Should be fixed by b34807d and c3b8eef
