### ISSUE TITLE
Permission denied on /tmp/git-errors

### ISSUE THREAD

**Issue by borrate** [dracula/zsh#43]
I was trying out this zsh theme on a test user on my machine and I liked it so I installed it on my main user but the git branch wasn't showing on the prompt.
After some debugging I found out that it was throwing a `Permission denied on/tmp/git-errors` because the owner was my test account.
I changed the ownership and fixed the issue but I was thinking that maybe it would be good to include the username or somenthing on the git-errors directory so it doesn't happen on multi-user machines.

**Comment by avalonwilliams** [comment]
Thanks for the info, to be honest, I have no clue why I even redirected it to that file in the first place, it seems much
more logical to just redirect the errors to /dev/null instead
of writing them to a file. I think it might've been because
of some testing I was doing at some point. I'll write up a
commit fixing this real quick.
